# Generated by Django 4.2.7 on 2025-08-02 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devEUI', models.CharField(help_text='Device EUI identifier', max_length=16, unique=True)),
                ('latest_status', models.BooleanField(default=False, help_text='Latest payload status (True=passing, False=failing)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fCnt', models.IntegerField(help_text='Frame counter to prevent duplicate messages')),
                ('data', models.TextField(help_text='Base64 encoded data')),
                ('data_hex', models.CharField(blank=True, help_text='Hexadecimal representation of decoded data', max_length=255)),
                ('is_passing', models.BooleanField(default=False, help_text='Whether the payload indicates passing status')),
                ('rx_info', models.JSONField(default=list, help_text='Receive information from gateways')),
                ('tx_info', models.JSONField(default=dict, help_text='Transmit information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='payloads.device')),
            ],
            options={
                'db_table': 'payloads',
                'unique_together': {('device', 'fCnt')},
            },
        ),
    ]
